### PR TITLE
Reinstall and remove added

### PR DESCRIPTION
**Pull request by jarriztg**

### CODE REVIEW

**Comment by iicc1** [comment]
I believe this can be done just erasing auth file: `rm ../.telegram.cli/auth` and after launch the bot.
It will request again a phone and It will be solved.

**Comment by jarriztg** [comment]
this is to delete all DBTeam for any problem

**Comment by jarriztg** [comment]
and u will need  rm "-R"  to delete a folder empty XD

**Comment by iicc1** [comment]
Closed, now in #96

**Pull request closed without merging**
