### PR TITLE
patterns fixed

### PR DESCRIPTION
**Pull request by jarriztg**

### CODE REVIEW

**Comment by Josepdal** [comment]
That code is wrong :sob: 

`if matches[1] == '!plugins' or matches[1] == '#plugins' or matches[1] == '/plugins' then`

**Comment by jarriztg** [comment]
no Josep, are ok xD

**Comment by jarriztg** [comment]
test it

**Comment by Josepdal** [comment]
if you write to bot: `#plugins whatever`

matches[1] == #plugins 
msg.text == #plugins whatever

so msg.text cannot be equal to #plugins /plugins or !plugins

**Comment by jarriztg** [comment]
already

**Pull request merged**
