### PR TITLE
Update settings.lua

### PR DESCRIPTION
**Pull request by IamJavid**

### CODE REVIEW

**Comment by 3iran** [comment]
Nice

**Comment by Josepdal** [comment]
run function is not closed

**Comment by Josepdal** [comment]
#15

**Comment by Josepdal** [comment]
https://github.com/Josepdal/DBTeam/blob/master/plugins/settings.lua

**Comment by Josepdal** [comment]
https://github.com/Josepdal/DBTeam/blob/master/plugins/settings.lua.patch

**Comment by Josepdal** [comment]
https://github.com/Josepdal/DBTeam/blob/master/plugins/settings.lua.diff

**Comment by jack-peterson** [comment]
** 1456740639.528893 lua: .///bot/utils.lua:5: module 'serpent' not found:
        no field package.preload['serpent']
        no file '/usr/local/share/lua/5.2/serpent.lua'
        no file '/usr/local/share/lua/5.2/serpent/init.lua'
        no file '/usr/local/lib/lua/5.2/serpent.lua'
        no file '/usr/local/lib/lua/5.2/serpent/init.lua'
        no file '/usr/share/lua/5.2/serpent.lua'
        no file '/usr/share/lua/5.2/serpent/init.lua'
        no file './serpent.lua'
        no file '.luarocks/share/lua/5.2/serpent.lua'
        no file '.luarocks/share/lua/5.2/serpent/init.lua'
        no file '/usr/local/lib/lua/5.2/serpent.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.2/serpent.so'
        no file '/usr/lib/lua/5.2/serpent.so'
        no file '/usr/local/lib/lua/5.2/loadall.so'
        no file './serpent.so'
        no file '.luarocks/lib/lua/5.2/serpent.so'











fix this broblem

**Comment by iicc1** [comment]
@jack-peterson you are missing serpent package, it is a problem of your setup

**Comment by jack-peterson** [comment]
how can install this pack ? or fix this problem?
give me terminal code.

**Comment by Josepdal** [comment]
Added https://github.com/Josepdal/DBTeam/commit/c5e6c10f4223ec41deeb714f52cd8ab10fb9a98d

**Pull request closed without merging**
